<?php
require __DIR__ . '/auth.php'; requireAdmin(); require __DIR__ . '/layout.php';
$db=getDB(); $cards=shopCollectionCards(); $slug=$_GET['cat']??''; $category=shopCollectionCardBySlug($slug); $error='';
if($slug && !$category){header('Location: products.php');exit;}
if($_SERVER['REQUEST_METHOD']==='POST' && ($_POST['action']??'')==='delete'){$stmt=$db->prepare('UPDATE products SET is_active=0 WHERE id=?');$stmt->execute([(int)($_POST['product_id']??0)]);header('Location: products.php'.($slug?'?cat='.urlencode($slug):''));exit;}
$products=$category?getProductsByCategory($db,$slug):$db->query('SELECT p.*, c.name AS category_name FROM products p LEFT JOIN categories c ON c.id=p.category_id WHERE p.is_active=1 ORDER BY p.id DESC')->fetchAll();
adminHeader($category?$category['name'].' products':'Manage products'); ?>
<div class="admin-actions"><a class="btn btn-primary" href="add-product.php?cat=<?= e($slug) ?>">Add product</a><a class="btn btn-outline" href="dashboard.php">All categories</a><?php if($category): ?><a class="btn btn-outline" href="../category.php?cat=shop-collection&type=<?= e($slug) ?>" target="_blank">View on website</a><?php endif; ?></div>
<div class="admin-panel" style="margin-top:24px"><?php if(!$products): ?><p>No products yet. Add your first product above.</p><?php else: ?><table class="admin-table"><thead><tr><th>Product</th><th>Category</th><th>Price</th><th>Actions</th></tr></thead><tbody><?php foreach($products as $product): ?><tr><td><div class="admin-product-cell"><img src="../<?= e(productImageUrl($product['image'])) ?>" alt=""><span><?= e($product['name']) ?></span></div></td><td><?= e($product['category_name']) ?></td><td><?= formatPrice((float)$product['price']) ?></td><td><a class="btn btn-sm btn-outline" href="add-product.php?id=<?= (int)$product['id'] ?>">Edit</a><form method="post" class="inline-form" onsubmit="return confirm('Remove this product from the website?')"><?= adminTokenField() ?><input type="hidden" name="action" value="delete"><input type="hidden" name="product_id" value="<?= (int)$product['id'] ?>"><button class="btn btn-sm btn-danger">Remove</button></form></td></tr><?php endforeach; ?></tbody></table><?php endif; ?></div><?php adminFooter(); ?>
